#!/bin/bash

if [ $# != 2 ]
then
  echo "usage: deploy <bucket-name> <stack-name>"
  exit 1
fi

aws cloudformation package --template-file cloud-formation-template.yaml --s3-bucket $1 --output-template-file cloud-formation-deploy.yaml

aws cloudformation deploy --template-file cloud-formation-deploy.yaml --stack-name $2 --capabilities CAPABILITY_IAM